okta:
  oauth2:
    issuer: https://dev-702677.okta.com/oauth2/default
    client-id: 0oa5hcq09ATvur0Jd4x6
    client-secret: p1uOXMPbUt_5Ol0s919Tjwnl6CTvoDswqG3zv--y
spring:
  thymeleaf:
    cache: false