spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: b4339eb1d2d6d915f336
            client-secret: 02c7736a93987319e285c79b5a7b8d07269557b1